import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type PaymentDocument = Payment & Document;

@Schema({ timestamps: true, collection: 'payments' })
export class Payment {
  @Prop({ type: Types.ObjectId, ref: 'Order', required: true })
  orderId: Types.ObjectId;

  @Prop({ type: String, required: true, unique: true })
  transactionId: string; // The MD5 hash generated by Bakong

  @Prop({ type: Number, required: true })
  amount: number;

  @Prop({ type: String, enum: ['USD', 'KHR'], default: 'USD' })
  currency: string;

  @Prop({ type: String, enum: ['PENDING', 'COMPLETED', 'FAILED'], default: 'PENDING' })
  status: string;

  @Prop({ type: String, required: true })
  qrRawString: string; // The EMV-compliant string generated by the Bakong SDK
}

export const PaymentSchema = SchemaFactory.createForClass(Payment);